
// This file has been generated by the GUI designer. Do not modify.

public partial class LoginDialog
{
	private global::Gtk.Table table;
	private global::Gtk.Entry entryMail;
	private global::Gtk.Entry entryPass;
	private global::Gtk.Label labelMail;
	private global::Gtk.Label labelPass;
	private global::Gtk.Button buttonCancel;
	private global::Gtk.Button buttonOk;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget LoginDialog
		this.Name = "LoginDialog";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Modal = true;
		this.Resizable = false;
		this.AllowGrow = false;
		// Internal child LoginDialog.VBox
		global::Gtk.VBox w1 = this.VBox;
		w1.Name = "dialog_VBox";
		w1.BorderWidth = ((uint)(2));
		// Container child dialog_VBox.Gtk.Box+BoxChild
		this.table = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table.Name = "table";
		this.table.RowSpacing = ((uint)(6));
		this.table.ColumnSpacing = ((uint)(6));
		// Container child table.Gtk.Table+TableChild
		this.entryMail = new global::Gtk.Entry ();
		this.entryMail.CanFocus = true;
		this.entryMail.Name = "entryMail";
		this.entryMail.IsEditable = true;
		this.entryMail.InvisibleChar = '●';
		this.table.Add (this.entryMail);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table [this.entryMail]));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.entryPass = new global::Gtk.Entry ();
		this.entryPass.CanFocus = true;
		this.entryPass.Name = "entryPass";
		this.entryPass.IsEditable = false;
		this.entryPass.Visibility = false;
		this.entryPass.InvisibleChar = '•';
		this.table.Add (this.entryPass);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table [this.entryPass]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.labelMail = new global::Gtk.Label ();
		this.labelMail.Name = "labelMail";
		this.labelMail.LabelProp = global::Mono.Unix.Catalog.GetString ("メールアドレス");
		this.table.Add (this.labelMail);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table [this.labelMail]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table.Gtk.Table+TableChild
		this.labelPass = new global::Gtk.Label ();
		this.labelPass.Name = "labelPass";
		this.labelPass.LabelProp = global::Mono.Unix.Catalog.GetString ("パスワード");
		this.table.Add (this.labelPass);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table [this.labelPass]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		w1.Add (this.table);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.table]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		w6.Padding = ((uint)(6));
		// Internal child LoginDialog.ActionArea
		global::Gtk.HButtonBox w7 = this.ActionArea;
		w7.Name = "dialog_ActionArea";
		w7.Spacing = 10;
		w7.BorderWidth = ((uint)(5));
		w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child dialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonCancel = new global::Gtk.Button ();
		this.buttonCancel.CanDefault = true;
		this.buttonCancel.CanFocus = true;
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.UseStock = true;
		this.buttonCancel.UseUnderline = true;
		this.buttonCancel.Label = "gtk-cancel";
		this.AddActionWidget (this.buttonCancel, -6);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
		w8.Expand = false;
		w8.Fill = false;
		// Container child dialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonOk = new global::Gtk.Button ();
		this.buttonOk.CanDefault = true;
		this.buttonOk.CanFocus = true;
		this.buttonOk.Name = "buttonOk";
		this.buttonOk.UseStock = true;
		this.buttonOk.UseUnderline = true;
		this.buttonOk.Label = "gtk-ok";
		this.AddActionWidget (this.buttonOk, -5);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonOk]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 150;
		this.Show ();
	}
}
