
// This file has been generated by the GUI designer. Do not modify.
namespace NicoMonoViewer
{
	public partial class NicorepoWidgetItemSubComment
	{
		private global::Gtk.VBox vboxSub;
		private global::Gtk.VBox vboxItem;
		private global::Gtk.HBox hboxPost;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NicoMonoViewer.NicorepoWidgetItemSubComment
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NicoMonoViewer.NicorepoWidgetItemSubComment";
			// Container child NicoMonoViewer.NicorepoWidgetItemSubComment.Gtk.Container+ContainerChild
			this.vboxSub = new global::Gtk.VBox ();
			this.vboxSub.Name = "vboxSub";
			this.vboxSub.Spacing = 6;
			// Container child vboxSub.Gtk.Box+BoxChild
			this.vboxItem = new global::Gtk.VBox ();
			this.vboxItem.Name = "vboxItem";
			this.vboxItem.Spacing = 6;
			this.vboxSub.Add (this.vboxItem);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxSub [this.vboxItem]));
			w1.Position = 0;
			// Container child vboxSub.Gtk.Box+BoxChild
			this.hboxPost = new global::Gtk.HBox ();
			this.hboxPost.Name = "hboxPost";
			this.hboxPost.Spacing = 6;
			this.vboxSub.Add (this.hboxPost);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxSub [this.hboxPost]));
			w2.Position = 1;
			this.Add (this.vboxSub);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
