
// This file has been generated by the GUI designer. Do not modify.
namespace NicoMonoViewer
{
	public partial class NicorepoWidgetItemUserActionStamp
	{
		private global::Gtk.Frame frame;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vboxIcon;
		private global::Gtk.VBox vboxMain;
		private global::Gtk.HBox hboxMain;
		private global::Gtk.Button buttonUser;
		private global::Gtk.Label labelUser;
		private global::Gtk.Label labelSan;
		private global::Gtk.HBox hboxSub;
		private global::Gtk.Button buttonTitle;
		private global::Gtk.Label labelStamp;
		private global::Gtk.HBox hboxOther;
		private global::NicoMonoViewer.NicorepoWidgetItemSubLongago nicorepowidgetitemsublongago;
		private global::NicoMonoViewer.NicorepoWidgetItemSubNicoru nicorepowidgetitemsubnicoru;
		private global::Gtk.Label GtkLabel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NicoMonoViewer.NicorepoWidgetItemUserActionStamp
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NicoMonoViewer.NicorepoWidgetItemUserActionStamp";
			// Container child NicoMonoViewer.NicorepoWidgetItemUserActionStamp.Gtk.Container+ContainerChild
			this.frame = new global::Gtk.Frame ();
			this.frame.Name = "frame";
			this.frame.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox";
			this.hbox1.Spacing = 6;
			// Container child hbox.Gtk.Box+BoxChild
			this.vboxIcon = new global::Gtk.VBox ();
			this.vboxIcon.Name = "vboxIcon";
			this.vboxIcon.Spacing = 6;
			this.hbox1.Add (this.vboxIcon);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxIcon]));
			w1.Position = 0;
			// Container child hbox.Gtk.Box+BoxChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxMain = new global::Gtk.HBox ();
			this.hboxMain.Name = "hboxMain";
			this.hboxMain.Spacing = 6;
			// Container child hboxMain.Gtk.Box+BoxChild
			this.buttonUser = new global::Gtk.Button ();
			this.buttonUser.CanFocus = true;
			this.buttonUser.Name = "buttonUser";
			// Container child buttonUser.Gtk.Container+ContainerChild
			this.labelUser = new global::Gtk.Label ();
			this.labelUser.Name = "labelUser";
			this.labelUser.LabelProp = global::Mono.Unix.Catalog.GetString ("嘘ケーキ");
			this.buttonUser.Add (this.labelUser);
			this.buttonUser.Label = null;
			this.hboxMain.Add (this.buttonUser);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxMain [this.buttonUser]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxMain.Gtk.Box+BoxChild
			this.labelSan = new global::Gtk.Label ();
			this.labelSan.Name = "labelSan";
			this.labelSan.LabelProp = global::Mono.Unix.Catalog.GetString ("さんがスタンプを取得しました。");
			this.hboxMain.Add (this.labelSan);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxMain [this.labelSan]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vboxMain.Add (this.hboxMain);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxMain]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxSub = new global::Gtk.HBox ();
			this.hboxSub.Name = "hboxSub";
			this.hboxSub.Spacing = 6;
			// Container child hboxSub.Gtk.Box+BoxChild
			this.buttonTitle = new global::Gtk.Button ();
			this.buttonTitle.CanFocus = true;
			this.buttonTitle.Name = "buttonTitle";
			// Container child buttonTitle.Gtk.Container+ContainerChild
			this.labelStamp = new global::Gtk.Label ();
			this.labelStamp.Name = "labelStamp";
			this.labelStamp.LabelProp = global::Mono.Unix.Catalog.GetString ("嘘ケーキ");
			this.buttonTitle.Add (this.labelStamp);
			this.buttonTitle.Label = null;
			this.hboxSub.Add (this.buttonTitle);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxSub [this.buttonTitle]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			this.vboxMain.Add (this.hboxSub);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxSub]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox1.Add (this.vboxMain);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxMain]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.hboxOther = new global::Gtk.HBox ();
			this.hboxOther.Name = "hboxOther";
			this.hboxOther.Spacing = 6;
			// Container child hboxOther.Gtk.Box+BoxChild
			this.nicorepowidgetitemsublongago = new global::NicoMonoViewer.NicorepoWidgetItemSubLongago ();
			this.nicorepowidgetitemsublongago.Events = ((global::Gdk.EventMask)(256));
			this.nicorepowidgetitemsublongago.Name = "nicorepowidgetitemsublongago";
			this.hboxOther.Add (this.nicorepowidgetitemsublongago);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxOther [this.nicorepowidgetitemsublongago]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hboxOther.Gtk.Box+BoxChild
			this.nicorepowidgetitemsubnicoru = new global::NicoMonoViewer.NicorepoWidgetItemSubNicoru ();
			this.nicorepowidgetitemsubnicoru.WidthRequest = 120;
			this.nicorepowidgetitemsubnicoru.Events = ((global::Gdk.EventMask)(256));
			this.nicorepowidgetitemsubnicoru.Name = "nicorepowidgetitemsubnicoru";
			this.hboxOther.Add (this.nicorepowidgetitemsubnicoru);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxOther [this.nicorepowidgetitemsubnicoru]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox.Add (this.hboxOther);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hboxOther]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.GtkAlignment.Add (this.vbox);
			this.frame.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>スタンプ獲得通知</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame.LabelWidget = this.GtkLabel;
			this.Add (this.frame);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
