
// This file has been generated by the GUI designer. Do not modify.

public partial class NicorepoMainWidget
{
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget NicorepoMainWidget
		global::Stetic.BinContainer.Attach (this);
		this.Name = "NicorepoMainWidget";
		// Container child NicorepoMainWidget.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add (this.textview1);
		this.Add (this.GtkScrolledWindow);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
		this.Shown += new global::System.EventHandler (this.OnShown);
	}
}
