
// This file has been generated by the GUI designer. Do not modify.
namespace NicoMonoViewer
{
	public partial class NicorepoWidgetItemSubLongago
	{
		private global::Gtk.Label label;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NicoMonoViewer.NicorepoWidgetItemSubLongago
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NicoMonoViewer.NicorepoWidgetItemSubLongago";
			// Container child NicoMonoViewer.NicorepoWidgetItemSubLongago.Gtk.Container+ContainerChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("嘘ケーキ");
			this.Add (this.label);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
