
// This file has been generated by the GUI designer. Do not modify.
namespace NicoMonoViewer
{
	public partial class NicorepoWidgetItemSubIcon48
	{
		private global::Gtk.Image image;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NicoMonoViewer.NicorepoWidgetItemSubIcon48
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 48;
			this.HeightRequest = 48;
			this.Name = "NicoMonoViewer.NicorepoWidgetItemSubIcon48";
			// Container child NicoMonoViewer.NicorepoWidgetItemSubIcon48.Gtk.Container+ContainerChild
			this.image = new global::Gtk.Image ();
			this.image.WidthRequest = 48;
			this.image.HeightRequest = 48;
			this.image.Name = "image";
			this.Add (this.image);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
