
// This file has been generated by the GUI designer. Do not modify.
namespace NicoMonoViewer
{
	public partial class NicorepoWidgetItemSubNicoru
	{
		private global::Gtk.Button button;
		private global::Gtk.HBox hbox;
		private global::Gtk.Image image;
		private global::Gtk.Arrow arrow;
		private global::Gtk.Label label;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NicoMonoViewer.NicorepoWidgetItemSubNicoru
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NicoMonoViewer.NicorepoWidgetItemSubNicoru";
			// Container child NicoMonoViewer.NicorepoWidgetItemSubNicoru.Gtk.Container+ContainerChild
			this.button = new global::Gtk.Button ();
			this.button.WidthRequest = 120;
			this.button.CanFocus = true;
			this.button.Name = "button";
			// Container child button.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			// Container child hbox.Gtk.Box+BoxChild
			this.image = new global::Gtk.Image ();
			this.image.WidthRequest = 20;
			this.image.HeightRequest = 20;
			this.image.Name = "image";
			this.hbox.Add (this.image);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox [this.image]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.arrow = new global::Gtk.Arrow (((global::Gtk.ArrowType)(2)), ((global::Gtk.ShadowType)(0)));
			this.arrow.Name = "arrow";
			this.hbox.Add (this.arrow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox [this.arrow]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("ロード中...");
			this.hbox.Add (this.label);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox [this.label]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.button.Add (this.hbox);
			this.button.Label = null;
			this.Add (this.button);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.hbox.Hide ();
			this.Show ();
			this.button.Clicked += new global::System.EventHandler (this.OnButtonClicked);
		}
	}
}
